name: adb_tools
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cmd_plus: ^1.3.3
  cross_file: ^0.3.4+2
  desktop_drop: ^0.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  process_run: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/adb-win/
    - assets/scrcpy-win64/
    - lib/images/
