name: Build ADB Tools
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
      - run: flutter build windows
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          path: 'build\windows\x64\runner\Release'
          type: 'zip'
          filename: 'ADBTools.zip'
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: upload zip file
          path: build\windows\x64\runner\Release\ADBTools.zip
